set -ga terminal-overrides ",xterm-256color*:Tc"
set -s escape-time 0
set-option -g renumber-windows on
bind-key '[' select-window -t 1
bind-key '{' select-window -t 2
bind-key '(' select-window -t 3
bind-key '$' select-window -t 4
bind-key '&' select-window -t 5
bind-key '=' select-window -t 6
bind-key '_' select-window -t 7
bind-key ')' select-window -t 8
bind-key '}' select-window -t 9

unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

bind-key v copy-mode
set-window-option -g mode-keys vi
set -s set-clipboard on
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'tmux load-buffer -w -'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r l select-pane -L
bind -r h select-pane -R

bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5
bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5

bind o split-window -h

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'

bind-key l switch-client -l
bind-key n switch-client -t n
bind-key m switch-client -t m
bind-key a switch-client -t a
bind-key t switch-client -t t
bind-key s choose-tree -s
